name: CPAD APP Backend Deployment

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to Cloud Foundry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pre Requisites
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli
          cf login -a ${{secrets.CF_ENDPOINT}} -u ${{secrets.CF_USERNAME}} -p ${{secrets.CF_PASSWORD}} -o ${{secrets.CF_ORG}} -s dev
          cf push